---

- name: Ensure rsyslog is present
  ansible.builtin.package:
    name: rsyslog
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Get rsyslog version
  ansible.builtin.set_fact:
    rsyslog_v: "{{ ansible_facts.packages['rsyslog'][0]['version'] }}"

- name: Debug | rsyslog version
  ansible.builtin.debug:
    var: rsyslog_v
    verbosity: 1

- name: Ensure base directory exists
  ansible.builtin.file:
    dest: "{{ tailon_syslog_target | dirname }}"
    state: directory
    mode: '0755'
    owner: "{{ syslog_user | default('root') }}"
    group: root
  when: >
    "'/var/log/' in tailon_syslog_target" and
    tailon_syslog_target|dirname != '/var/log'

- name: Setup rsyslog to send tailon logs to a specific target
  ansible.builtin.template:
    src: rsyslog-tailon.conf.j2
    dest: /etc/rsyslog.d/30-tailon.conf
    mode: '0644'
    backup: yes
  notify:
    - Restart rsyslog

# only if file, not if remote syslog
- name: Import logrotate
  ansible.builtin.import_tasks: logrotate.yml
  when: "'/var/log/' in tailon_syslog_target"
